Sql exercises
ilz-code/sql-training pull request #1
Opened 2021-09-07 13:48 UTC by ilz-code

2021-09-07 19:46 UTC, ausmoons requested changes

2021-09-07 19:46 UTC, ausmoons commented on sql-movies/jest.config.js
> +  preset: 'ts-jest',
/_db/08-database.sqlite3 ir lieki faili.

2021-09-07 19:46 UTC, ausmoons commented on sql-shopify/test/02-insert-data.test.ts
> +        `todo` +
Tu esi pabeigusi sql-shopify? Un main vajadzeja ielikt sakuma failus, lai var saprast kādas izmaiņas ir veiktas

2021-09-07 19:54 UTC, ilz-code commented on sql-shopify/test/02-insert-data.test.ts
> +        `todo` +
Nē, shopify vēl nepabeidzu. Sāku kļūdas pēc šajā zarā, pēc tam pārgāju uz citu

2021-09-07 19:59 UTC, ilz-code commented on sql-movies/jest.config.js
> +  preset: 'ts-jest',
Nevaru atrast liekus failus. Kur tos var redzēt?

2021-09-08 17:53 UTC, ausmoons commented on sql-movies/jest.config.js
> +  preset: 'ts-jest',
visi faili, kas ir zem _db ir lieki. Tie veidojas, kad tiek palaisti testi. Izdzēs lokāli no datora un iepusho izmaiņas.

2021-09-08 17:53 UTC, ausmoons commented on sql-shopify/test/02-insert-data.test.ts
> +        `todo` +
PR liek failus, kuri ir nepieciešami konkrētajam PR. Man iziet visi movie testi, bet nevaru apstirpināt ar liekiem failiem

2021-09-08 18:50 UTC, ausmoons requested changes
Tev ir jāizņem arī sql-shopify vai jāiepusho ejoši testi

2021-09-09 16:57 UTC, ausmoons approved these changes

2021-09-10 05:24 UTC, merged